// ─── oh-my-hermes template engine ───────────────────────────────────────────
//
// Generates CLAUDE.md, AGENTS.md, and .claude/settings.local.json from
// project metadata.  Templates embed the expert-team system, magic keywords,
// agent catalog, and session rules used by oh-my-hermes.
// ─────────────────────────────────────────────────────────────────────────────

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ProjectInfo {
  name: string;
  stack: string[];
  frameworks: string[];
  description: string;
}

// ─── CLAUDE.md Generator ────────────────────────────────────────────────────

/**
 * Generate a full CLAUDE.md tailored to the project.
 *
 * Includes:
 *  - Expert team system prompt
 *  - Magic keywords
 *  - Agent catalog
 *  - Session rules
 *  - Project-specific stack/framework guidance
 */
export function generateClaudeMd(projectInfo: ProjectInfo): string {
  const stackList = projectInfo.stack.length > 0
    ? projectInfo.stack.join(', ')
    : 'not detected';

  const frameworkList = projectInfo.frameworks.length > 0
    ? projectInfo.frameworks.join(', ')
    : 'none detected';

  return `# ${projectInfo.name} — CLAUDE.md
> Auto-generated by oh-my-hermes (omh). Edit freely; omh will not overwrite your changes.

## Project Overview
${projectInfo.description || `This is the ${projectInfo.name} project.`}

**Stack:** ${stackList}
**Frameworks:** ${frameworkList}

---

## Expert Team System

You have access to a virtual team of domain experts. When a task requires specialized knowledge, mentally adopt the persona of the relevant expert before responding.

### Core Experts
| Expert | Domain | When to invoke |
|--------|--------|----------------|
| **Architect** | System design, patterns, trade-offs | Architecture decisions, module boundaries |
| **Security** | Auth, secrets, vulnerabilities | Auth flows, API keys, input validation |
| **Performance** | Profiling, optimization, caching | Slow queries, bundle size, memory leaks |
| **DevOps** | CI/CD, Docker, infra-as-code | Deployment, pipelines, environment config |
| **QA** | Testing strategies, edge cases | Test coverage, regression risks |
| **DX** | Developer experience, tooling | CLI design, error messages, documentation |

### Stack-Specific Experts
${generateStackExperts(projectInfo)}

### How to Invoke
Use the expert's name as a keyword at the start of your prompt:
\`\`\`
@Architect Should we use a monorepo or polyrepo?
@Security Review this auth middleware for vulnerabilities.
@Performance Profile this database query.
\`\`\`

---

## Magic Keywords

These keywords trigger specific behaviors:

| Keyword | Behavior |
|---------|----------|
| \`/think\` | Deep reasoning mode — show your thought process step by step |
| \`/review\` | Code review mode — critique the code for bugs, style, security |
| \`/test\` | Generate tests for the specified code |
| \`/refactor\` | Refactor with explanations of each improvement |
| \`/explain\` | Explain the code as if teaching a junior developer |
| \`/plan\` | Create a detailed implementation plan before writing code |
| \`/debug\` | Systematic debugging — hypothesize, test, narrow down |
| \`/handoff\` | Prepare session summary for handoff to another tool |
| \`/status\` | Show current session progress and pending tasks |
| \`/decide\` | Log an architectural decision with reasoning |

---

## Agent Catalog

Available agents for delegation (via Claude Code sub-agents):

| Agent | Purpose | Invocation |
|-------|---------|------------|
| **Researcher** | Search code, find patterns, read docs | Automatic for exploration tasks |
| **Implementer** | Write and modify source code | Automatic for coding tasks |
| **Reviewer** | Review changes before commit | \`/review\` or pre-commit |
| **Tester** | Write and run tests | \`/test\` keyword |
| **Documenter** | Generate documentation | When modifying public APIs |

---

## Session Rules

1. **Session Continuity**: At the start of each conversation, check for \`.omh/sessions/\` for previous context. Load the most recent session if available.
2. **Decision Logging**: When making architectural decisions, record them in shared memory via \`/decide\`.
3. **Progress Tracking**: Update task progress as you work. Mark tasks completed, note blockers.
4. **Handoff Readiness**: When ending a session, use \`/handoff\` to prepare context for the next session (same tool or cross-tool).
5. **File Tracking**: Keep track of all files you modify during the session.
6. **No Secrets**: Never write API keys, passwords, or tokens into tracked files.

---

## Project Conventions
${generateProjectConventions(projectInfo)}

---

## Cross-Tool Awareness

This project uses **oh-my-hermes** for multi-tool orchestration. Sessions may alternate between:
- **Claude Code** (this tool) — for complex reasoning, architecture, full-feature implementation
- **Codex CLI** — for rapid targeted edits, bulk refactoring, automation

Check \`.omh/shared-memory/\` for decisions and progress from other tools.
Check \`.omh/handoffs/\` for context passed between tools.
`;
}

// ─── AGENTS.md Generator ────────────────────────────────────────────────────

/**
 * Generate AGENTS.md with equivalent content for Codex CLI.
 *
 * Codex uses a more concise instruction style. The content mirrors CLAUDE.md
 * but is structured as direct instructions rather than a conversational guide.
 */
export function generateAgentsMd(projectInfo: ProjectInfo): string {
  const stackList = projectInfo.stack.length > 0
    ? projectInfo.stack.join(', ')
    : 'not detected';

  const frameworkList = projectInfo.frameworks.length > 0
    ? projectInfo.frameworks.join(', ')
    : 'none detected';

  return `# ${projectInfo.name} — AGENTS.md
> Auto-generated by oh-my-hermes (omh). Edit freely; omh will not overwrite your changes.

## Project
${projectInfo.description || `${projectInfo.name} project.`}

- **Stack:** ${stackList}
- **Frameworks:** ${frameworkList}

## Instructions

### General
- Follow existing code style and conventions in this repository.
- Write clean, well-typed code. Prefer explicit types over \`any\`.
- Keep functions small and focused.
- Add comments only where intent is non-obvious.
- Never write secrets, API keys, or credentials to files.

### Session Awareness
- Check \`.omh/sessions/\` for previous session context before starting.
- Check \`.omh/handoffs/\` for context passed from Claude Code or previous Codex sessions.
- Track files you modify for session summary.

### Expert Roles
When handling specialized tasks, apply domain expertise:
- **Architecture**: Consider module boundaries, coupling, scalability.
- **Security**: Validate inputs, check auth flows, avoid exposing secrets.
- **Performance**: Watch for N+1 queries, unnecessary re-renders, large bundles.
- **Testing**: Write meaningful tests; cover edge cases and error paths.

### Decision Protocol
When making significant decisions:
1. State the decision clearly.
2. List alternatives considered.
3. Explain the reasoning.
4. Note any trade-offs.

${generateProjectConventions(projectInfo)}

## Cross-Tool Orchestration
This project uses oh-my-hermes. Work may alternate between Codex CLI (this tool) and Claude Code. Check \`.omh/shared-memory/memory.json\` for shared context and decisions.

## File Structure
\`\`\`
.omh/                  # oh-my-hermes state
  sessions/            # Session history (per-tool)
  shared-memory/       # Cross-tool shared context
  handoffs/            # Handoff documents between tools
  config.json          # OMH configuration
\`\`\`
`;
}

// ─── Settings Generator ─────────────────────────────────────────────────────

/**
 * Generate `.claude/settings.local.json` with sensible defaults.
 */
export function generateSettings(projectInfo: ProjectInfo): Record<string, unknown> {
  const permissions: string[] = [
    // File operations
    'Bash(cat:*)',
    'Bash(ls:*)',
    'Bash(find:*)',
    'Bash(head:*)',
    'Bash(tail:*)',
    'Bash(wc:*)',
    'Bash(grep:*)',
    'Bash(rg:*)',
    // Version control
    'Bash(git:*)',
    // Directory operations
    'Bash(mkdir:*)',
    'Bash(cp:*)',
    'Bash(mv:*)',
  ];

  // Add stack-specific permissions
  if (projectInfo.stack.some((s) => s.includes('typescript') || s.includes('javascript'))) {
    permissions.push(
      'Bash(npm:*)',
      'Bash(npx:*)',
      'Bash(node:*)',
      'Bash(tsc:*)',
    );
  }

  if (projectInfo.stack.some((s) => s.includes('python'))) {
    permissions.push(
      'Bash(python:*)',
      'Bash(python3:*)',
      'Bash(pip:*)',
      'Bash(pip3:*)',
      'Bash(pytest:*)',
    );
  }

  if (projectInfo.stack.some((s) => s.includes('rust'))) {
    permissions.push(
      'Bash(cargo:*)',
      'Bash(rustc:*)',
    );
  }

  if (projectInfo.stack.some((s) => s.includes('go'))) {
    permissions.push(
      'Bash(go:*)',
    );
  }

  if (projectInfo.stack.some((s) => s.includes('docker'))) {
    permissions.push(
      'Bash(docker:*)',
      'Bash(docker-compose:*)',
    );
  }

  return {
    permissions,
    deny: [],
  };
}

// ─── Internal Helpers ───────────────────────────────────────────────────────

function generateStackExperts(info: ProjectInfo): string {
  const experts: string[] = [];

  if (info.stack.some((s) => s.includes('typescript') || s.includes('javascript'))) {
    experts.push('| **TypeScript** | Types, generics, module system | Complex type definitions, module architecture |');
    experts.push('| **Node.js** | Runtime, async patterns, streams | Server-side logic, API design |');
  }

  if (info.frameworks.includes('next.js')) {
    experts.push('| **Next.js** | SSR, RSC, routing, data fetching | Page architecture, API routes, caching |');
  }

  if (info.frameworks.includes('react') || info.frameworks.includes('next.js')) {
    experts.push('| **React** | Components, hooks, state management | UI architecture, performance optimization |');
  }

  if (info.stack.some((s) => s.includes('python'))) {
    experts.push('| **Python** | Pythonic patterns, async, typing | Python-specific design, package management |');
  }

  if (info.frameworks.includes('django')) {
    experts.push('| **Django** | ORM, views, middleware, admin | Model design, query optimization, auth |');
  }

  if (info.stack.some((s) => s.includes('rust'))) {
    experts.push('| **Rust** | Ownership, lifetimes, traits, macros | Memory safety, zero-cost abstractions |');
  }

  if (info.stack.some((s) => s.includes('go'))) {
    experts.push('| **Go** | Goroutines, channels, interfaces | Concurrency patterns, service design |');
  }

  if (info.stack.some((s) => s.includes('docker'))) {
    experts.push('| **Container** | Docker, compose, orchestration | Image optimization, multi-stage builds |');
  }

  if (experts.length === 0) {
    return '_No stack-specific experts detected. Add your stack to `.omh/config.json` to get tailored experts._';
  }

  return '| Expert | Domain | When to invoke |\n|--------|--------|----------------|\n' + experts.join('\n');
}

function generateProjectConventions(info: ProjectInfo): string {
  const conventions: string[] = [];

  if (info.stack.some((s) => s.includes('typescript'))) {
    conventions.push(`### TypeScript Conventions`);
    conventions.push(`- Use \`import type\` for type-only imports.`);
    conventions.push(`- Prefer \`interface\` over \`type\` for object shapes.`);
    conventions.push(`- Use \`.js\` extensions in import paths (for ESM compatibility).`);
    conventions.push(`- Use \`node:\` prefix for built-in modules (\`node:fs\`, \`node:path\`).`);
    conventions.push('');
  }

  if (info.stack.some((s) => s.includes('python'))) {
    conventions.push(`### Python Conventions`);
    conventions.push(`- Use type hints for all function signatures.`);
    conventions.push(`- Follow PEP 8 style guidelines.`);
    conventions.push(`- Use \`pathlib.Path\` over \`os.path\` for file operations.`);
    conventions.push('');
  }

  if (info.stack.some((s) => s.includes('rust'))) {
    conventions.push(`### Rust Conventions`);
    conventions.push(`- Follow Rust API Guidelines.`);
    conventions.push(`- Use \`thiserror\` for library errors, \`anyhow\` for application errors.`);
    conventions.push(`- Prefer \`&str\` over \`String\` in function parameters.`);
    conventions.push('');
  }

  if (info.stack.some((s) => s.includes('go'))) {
    conventions.push(`### Go Conventions`);
    conventions.push(`- Follow Effective Go guidelines.`);
    conventions.push(`- Use \`context.Context\` as the first parameter.`);
    conventions.push(`- Return errors; do not panic.`);
    conventions.push('');
  }

  if (conventions.length === 0) {
    conventions.push('_Follow the existing conventions in this codebase._');
    conventions.push('');
  }

  return conventions.join('\n');
}
